import Vue from "vue"
import {
  ActionSheet,
  AddressEdit,
  AddressList,
  Area,
  Button,
  Card,
  Cell,
  CellGroup,
  Checkbox,
  CheckboxGroup,
  Circle,
  Col,
  Collapse,
  CollapseItem,
  ContactCard,
  ContactEdit,
  ContactList,
  Coupon,
  CouponCell,
  CouponList,
  DatetimePicker,
  Dialog,
  Field,
  Grid,
  GridItem,
  GoodsAction,
  Icon,
  Image,
  ImagePreview,
  Info,
  Lazyload,
  List,
  Loading,
  Locale,
  NavBar,
  NoticeBar,
  Notify,
  NumberKeyboard,
  Overlay,
  Pagination,
  Panel,
  PasswordInput,
  Picker,
  Popup,
  Progress,
  PullRefresh,
  Radio,
  RadioGroup,
  Rate,
  Row,
  Search,
  Sku,
  Slider,
  Step,
  Stepper,
  Steps,
  Sticky,
  SubmitBar,
  Swipe,
  SwipeCell,
  SwipeItem,
  Switch,
  SwitchCell,
  Tab,
  Tabbar,
  TabbarItem,
  Tabs,
  Tag,
  Toast,
  TreeSelect,
  Uploader
} from 'vant'
import 'vant/lib/index.css'

Vue.use(ActionSheet)
Vue.use(AddressEdit)
Vue.use(AddressList)
Vue.use(Area)
Vue.use(Button)
Vue.use(Card)
Vue.use(Cell)
Vue.use(CellGroup)
Vue.use(Checkbox)
Vue.use(CheckboxGroup)
Vue.use(Circle)
Vue.use(Col)
Vue.use(Collapse)
Vue.use(CollapseItem)
Vue.use(ContactCard)
Vue.use(ContactEdit)
Vue.use(ContactList)
Vue.use(Coupon)
Vue.use(CouponCell)
Vue.use(CouponList)
Vue.use(DatetimePicker)
Vue.use(Dialog)
Vue.use(Field)
Vue.use(Grid)
Vue.use(GridItem)
Vue.use(GoodsAction)
Vue.use(Icon)
Vue.use(Image)
Vue.use(ImagePreview)
Vue.use(Info)
Vue.use(Lazyload)
Vue.use(List)
Vue.use(Loading)
Vue.use(Locale)
Vue.use(NavBar)
Vue.use(NoticeBar)
Vue.use(Notify)
Vue.use(NumberKeyboard)
Vue.use(Overlay)
Vue.use(Pagination)
Vue.use(Panel)
Vue.use(PasswordInput)
Vue.use(Picker)
Vue.use(Popup)
Vue.use(Progress)
Vue.use(PullRefresh)
Vue.use(Radio)
Vue.use(RadioGroup)
Vue.use(Rate)
Vue.use(Row)
Vue.use(Search)
Vue.use(Sku)
Vue.use(Slider)
Vue.use(Step)
Vue.use(Stepper)
Vue.use(Steps)
Vue.use(Sticky)
Vue.use(SubmitBar)
Vue.use(Swipe)
Vue.use(SwipeCell)
Vue.use(SwipeItem)
Vue.use(Switch)
Vue.use(SwitchCell)
Vue.use(Tab)
Vue.use(Tabbar)
Vue.use(TabbarItem)
Vue.use(Tabs)
Vue.use(Tag)
Vue.use(Toast)
Vue.use(TreeSelect)
Vue.use(Uploader)